apiVersion: v1
kind: Secret
metadata:
  name: auth-service-secrets
  namespace: microservices
  labels:
    app: auth-service
    version: 1.0.0
type: Opaque
data:
  secret_key: Y2hhbmdlLW1lLXRvLWEtc2VjdXJlLWtleQ==
